export const data = [{
    index: 1,
    question: 'Какой банк в Росии самый популярный?',
    content1: 'Тинькофф',
    points1: 32,
    content2: 'Сбербанк',
    points2: 25,
    content3: 'ВТБ',
    points3: 15,
    content4: 'Альфа-Банк',
    points4: 11,
    content5: 'Открытие',
    points5: 5,
    content6: 'Райффайзен',
    points6: 3
  },{
    index: 2,
    question: 'Куда вложить деньги?',
    content1: 'Открыть счёт',
    points1: 34,
    content2: 'Купить акции',
    points2: 19,
    content3: 'Купить недвижимость',
    points3: 14,
    content4: 'В образование',
    points4: 9,
    content5: 'Купить биткоины',
    points5: 7,
    content6: 'Убрать их под подушку',
    points6: 6
  },{
    index: 3,
    question: 'Кем люди хотят стать когда вырастут?',
    content1: 'Менеджером',
    points1: 28,
    content2: 'Космонавтом',
    points2: 21,
    content3: 'Моряком',
    points3: 18,
    content4: 'Полицейским',
    points4: 13,
    content5: 'Президентом',
    points5: 8,
    content6: 'Программистом',
    points6: 2
  },{
    index: 4,
    question: 'Какой язык программирования самый популярный?',
    content1: 'Javascript',
    points1: 15,
    content2: 'Java',
    points2: 30,
    content3: 'Python',
    points3: 60,
    content4: 'PHP',
    points4: 120,
    content5: 'C',
    points5: 180,
    content6: 'Ruby',
    points6: 240
}]